# Generated by Django 3.1.2 on 2021-11-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_World', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
