# Generated by Django 3.1.2 on 2021-08-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='password',
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='0000000'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='0000000', max_length=122),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='0000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='0000000', max_length=122),
        ),
    ]
