# Generated by Django 3.1.2 on 2021-09-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0002_auto_20210830_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='0000000', max_length=122)),
                ('password', models.CharField(default='0000000', max_length=122)),
            ],
        ),
    ]
