# Generated by Django 3.1.2 on 2021-09-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0003_sign_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='name',
            field=models.CharField(default='0000000', max_length=122),
        ),
    ]
