# Generated by Django 3.1.2 on 2021-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0005_auto_20210917_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Firstname',
            field=models.TextField(default='0000000'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.TextField(default='0000000'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(default='0000000'),
        ),
    ]
