# Generated by Django 3.1.2 on 2021-09-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0006_auto_20210917_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Firstname',
            field=models.CharField(default='first name', max_length=122),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='password', max_length=122),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='username', max_length=122),
        ),
    ]
