# Generated by Django 3.1.2 on 2021-09-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0007_auto_20210917_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
