# Generated by Django 3.1.2 on 2021-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='0000000', max_length=122)),
                ('email', models.CharField(default='0000000', max_length=122)),
                ('first_name', models.CharField(default='0000000', max_length=122)),
                ('last_name', models.CharField(default='0000000', max_length=122)),
                ('password', models.CharField(default='0000000', max_length=122)),
            ],
        ),
    ]
