# Generated by Django 3.1.2 on 2021-09-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0010_auto_20210925_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='last_login',
        ),
    ]
