# Generated by Django 3.1.2 on 2021-09-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0011_remove_signup_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Username',
            field=models.CharField(default='Username', max_length=122),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default='Email', max_length=122),
        ),
        migrations.AlterField(
            model_name='signup',
            name='first_name',
            field=models.CharField(default='First Name', max_length=122),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=122),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default='password', max_length=122),
        ),
    ]
