# Generated by Django 3.1.2 on 2021-09-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0012_auto_20210925_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Username',
            new_name='username',
        ),
    ]
