# Generated by Django 3.1.2 on 2021-09-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0013_auto_20210925_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='Username',
        ),
    ]
