# Generated by Django 3.1.2 on 2021-09-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0014_auto_20210925_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Username',
        ),
    ]
