# Generated by Django 3.1.2 on 2021-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0015_remove_signup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Username',
            field=models.CharField(default='Username', max_length=122),
        ),
    ]
