# Generated by Django 3.1.2 on 2021-09-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0016_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
