# Generated by Django 3.1.2 on 2021-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0020_auto_20211010_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
