# Generated by Django 3.1.2 on 2021-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0021_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
