# Generated by Django 3.1.2 on 2021-10-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0023_book1_book2_book3_book4_book5_book6_book7_book8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book1',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Classics'),
        ),
        migrations.AlterField(
            model_name='book1',
            name='pdf',
            field=models.FileField(upload_to='Classics'),
        ),
    ]
