# Generated by Django 3.1.2 on 2021-10-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0024_auto_20211030_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book1',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Classics/covers'),
        ),
        migrations.AlterField(
            model_name='book1',
            name='pdf',
            field=models.FileField(upload_to='Classics/pdfs'),
        ),
        migrations.AlterField(
            model_name='book2',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='CBGN/covers/'),
        ),
        migrations.AlterField(
            model_name='book2',
            name='pdf',
            field=models.FileField(upload_to='CBGN/pdfs/'),
        ),
        migrations.AlterField(
            model_name='book3',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='DM/covers/'),
        ),
        migrations.AlterField(
            model_name='book3',
            name='pdf',
            field=models.FileField(upload_to='DM/pdfs/'),
        ),
        migrations.AlterField(
            model_name='book4',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Fantasy/covers/'),
        ),
        migrations.AlterField(
            model_name='book4',
            name='pdf',
            field=models.FileField(upload_to='Fantasy/pdfs/'),
        ),
        migrations.AlterField(
            model_name='book5',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='HF/covers/'),
        ),
        migrations.AlterField(
            model_name='book5',
            name='pdf',
            field=models.FileField(upload_to='HF/pdfs/'),
        ),
        migrations.AlterField(
            model_name='book6',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Horror/covers/'),
        ),
        migrations.AlterField(
            model_name='book6',
            name='pdf',
            field=models.FileField(upload_to='Horror/pdfs/'),
        ),
        migrations.AlterField(
            model_name='book7',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='LF/covers/'),
        ),
        migrations.AlterField(
            model_name='book7',
            name='pdf',
            field=models.FileField(upload_to='LF/pdfs/'),
        ),
        migrations.AlterField(
            model_name='book8',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Sci-fi/covers/'),
        ),
        migrations.AlterField(
            model_name='book8',
            name='pdf',
            field=models.FileField(upload_to='Sci-fi/pdfs/'),
        ),
    ]
