# Generated by Django 3.1.2 on 2021-10-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0025_auto_20211030_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book2',
            new_name='CBGN',
        ),
        migrations.RenameModel(
            old_name='Book1',
            new_name='Classics',
        ),
        migrations.RenameModel(
            old_name='Book3',
            new_name='DM',
        ),
        migrations.RenameModel(
            old_name='Book4',
            new_name='Fantasy',
        ),
        migrations.RenameModel(
            old_name='Book5',
            new_name='HF',
        ),
        migrations.RenameModel(
            old_name='Book6',
            new_name='Horror',
        ),
        migrations.RenameModel(
            old_name='Book7',
            new_name='LF',
        ),
        migrations.RenameModel(
            old_name='Book8',
            new_name='Sci_fi',
        ),
    ]
