# Generated by Django 3.1.2 on 2021-10-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0026_auto_20211030_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf', models.FileField(upload_to='AllBook/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='AllBook/covers/')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
