# Generated by Django 3.1.2 on 2021-10-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0028_auto_20211031_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act_adv',
            name='desc',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='all_book',
            name='desc',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='cbgn',
            name='desc',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='classics',
            name='desc',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='desc',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='fantasy',
            name='desc',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='hf',
            name='desc',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='horror',
            name='desc',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='lf',
            name='desc',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='sci_fi',
            name='desc',
            field=models.TextField(default='Description'),
        ),
    ]
