# Generated by Django 3.1.2 on 2021-11-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softy', '0029_auto_20211031_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
